version: '3'

services:

  redis:
    image: redis
    container_name: redis-server
    expose:
      - 6379

  app:
    container_name: 'routes-node'
    build: .
    command: npm start
    ports:
      - '1433:1433'
    volumes:
      - .:/usr/app
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis-server
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE_NAME=
      
  db:
    container_name: 'database-node'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - TZ=America/Sao_Paulo